### ISSUE TITLE
✨ 계층별 초기 모듈 구성

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#12]
### ✨ 진행할 작업 설명

```markdown
프로젝트 아키텍처 초기 설정 `DDD`기반 `4 Layered Architecture` 구성
application, domain, infrastructure, presentation 계층 구성
```

### 🚀 TODO

- [x]  Users 모듈 초기 설정 및 파일 추가
   - 사용자 관련 엔티티(user.entity.ts), 서비스(user.service.ts), 컨트롤러(user.controller.ts) 및 DTO 파일 생성
   - 사용자 CRUD 기능을 위한 API 엔드포인트 정의
 - [x] Quiz 모듈 초기 설정 및 파일 추가
   - ChoiceQuiz, Interview, ChoiceOption 엔티티 및 퀴즈 서비스, 컨트롤러 파일 추가
   - Category, Like 관련 서비스와 컨트롤러 파일 추가
- [x] Rankings 모듈 초기 설정 및 파일 추가
   - 랭킹 엔티티(ranking.entity.ts), 서비스 및 컨트롤러 파일 생성
- [x] PointHistory 모듈 초기 설정 및 파일 추가
   - 포인트 이력 엔티티, 서비스 및 컨트롤러 파일 생성

### 🐋 연관된 이슈

- closed
- resolved
