### ISSUE TITLE
✨ dev 서버 배포

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#17]
### ✨ 진행할 작업 설명

```markdown
dev 서버 배포를 진행합니다.
```

### 🚀 TODO

- [x] github action 스크립트 작성
- [x] Dockerfile 작성
- [x] ec2 생성 및 nginx, docker 등 설치
- [x] 도메인 구매 및 nginx 설정

### 🐋 연관된 이슈

- closed
- resolved
