### ISSUE TITLE
✨ 환경 변수 설정 파일 추가

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#2]
### ✨ 진행할 작업 설명

```markdown
환경변수를 효율적으로 관리하기 위한 작업 수행
```

### 🚀 TODO

- [x] cross-env 의존성 추가 및 npm script에 환경 별 적용
- [x] 환경 변수 검증 유틸 함수 추가
- [x] 환경 설정 타입 정의
