### ISSUE TITLE
✨ 카테고리 시드 파일 및 데이터소스 추가

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#21]
### ✨ 진행할 작업 설명

```markdown
데이터 베이스와 연결하기 위해 데이터 소스를 추가합니다.
시드 파일 처리를 위해 시드 모듈과 시드 실행 파일을 추가합니다.
초기 카테고리 정보 삽입을 위한 카테고리 시드 파일을 추가합니다.
```

### 🚀 TODO

- [x] 데이터 소스 추가
- [x] 시드 모듈과 실행 파일 추가
- [x] 카테고리 시드 파일 추가

### 🐋 연관된 이슈

- closed 
- resolved
