### ISSUE TITLE
♻️ 인터뷰 목록 조회와 상세 조회 분리 

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#30]
### ♻️ 진행할 작업 설명

```markdown
인터뷰 전체 목록 조회의 데이터에서 불필요한 응답을 제외시키고, 인터뷰 상세 조회 기능을 추가합니다.
```

### ☘️TODO

- [x] 인터뷰 메서드 및 DTO 네이밍 통일
- [x] 인터뷰 상세 조회 기능 추가
- [x] 인터뷰 목록 조회 응답 형식 변경

### 🐋 연관된 이슈

- closed
- resolved
