### ISSUE TITLE
✨ 인터뷰 좋아요 기능 추가

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#32]
### ✨ 진행할 작업 설명

```markdown
인터뷰와 관련된 좋아요 기능을 추가하고, 인터뷰 조회 시 사용자의 좋아요 상태를 함께 반환하도록 개선합니다.
```

### 🚀 TODO

- [ ] 좋아요 엔티티 및 관계 설정
- [ ] 좋아요 토글 기능 구현
- [ ] 인터뷰 조회시 좋아요 상태 포함

### 🐋 연관된 이슈

- closed
- resolved
