### ISSUE TITLE
✨ Swagger 설정

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#4]
### ✨ 진행할 작업 설명

```markdown
FE 개발자와의 협업을 위해 Swagger설정을 통해 API를 문서화
`http://localhost:3000/docs` 에서 확인 가능
Swagger 설정 및 User API 테스트 엔드포인트 추가
```

### 🚀 TODO

- [x] Swagger 관련 의존성 추가
- [x] Swagger UI 설정 추가
- [x] Swagger 테스트 겸용 User API 엔드포인트 추가
- [x] Swagger 응답 데코레이터 추가
- [x] Swagger 인증 설정 추가
