### ISSUE TITLE
✨ 카카오 로그인 구현

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#7]
### ✨ 진행할 작업 설명

```markdown
카카오 소셜 로그인 기능을 구현하여 사용자가 카카오 계정을 통해 로그인할 수 있도록 합니다. 카카오 로그인 API를 통해 인증을 처리하고, 카카오 유저 정보를 조회하여 필요한 유저 데이터를 관리합니다.
```

### 🚀 TODO

- [x] 카카오 로그인 API 연동 및 로그인 엔드포인트 구현
- [x] 카카오 인증 클라이언트 설정 및 토큰 발급 로직 작성
- [x] 유저 정보 조회 및 필요한 유저 타입 정의
- [x] 카카오 로그인 리다이렉트 및 콜백 엔드포인트 구성

### 🐋 연관된 이슈

- closed
- resolved #8
