### ISSUE TITLE
✨ JWT 토큰 발급 및 인증 설정

### ISSUE THREAD

**Issue by jjikky** [sen-jik/cs-hub-be#8]
### ✨ 진행할 작업 설명

```markdown
카카오 로그인 이후, JWT 토큰 발급 로직을 추가하여 사용자가 인증된 상태를 유지할 수 있도록 합니다. 발급된 JWT를 쿠키에 저장하고, 인증에 필요한 설정을 적용합니다.
```

### 🚀 TODO

- [x] JWT 토큰 생성 로직 추가 및 토큰을 쿠키에 저장하는 설정 구현
- [x] JWT Payload 타입 정의 및 Strategy 설정
- [x] 인증 모듈 구성 및 기본 의존성 주입

### 🐋 연관된 이슈

- closed
- resolved #7
